### ISSUE TITLE
can it handle mca files?

### ISSUE THREAD

**Issue by greplol** [MikuAuahDark/lua-nbt#2]
it keeps returning `ServerStorage.Script.ModuleScript:1179: unknown tag ID 60 at 8551`

**Comment by MikuAuahDark** [comment]
Sounds like a bug when parsing. Do you have the problematic mca file?

Please note that this lua-nbt does **not** handle compression. If it's compressed with gzip or lz4, you have to decompress it yourself.

**Comment by greplol** [comment]
how can i know how mine mca is compressed?

**Comment by MikuAuahDark** [comment]
If the file starts with `1f 8b` then it's gzip compressed. If the file starts with `04 22 4d 18` then it's lz4 compressed.

**Comment by greplol** [comment]
uh where? 
![image](https://github.com/MikuAuahDark/lua-nbt/assets/86880670/dd3c63fc-3447-4ad3-a8c9-6e8fa9de6845)

**Comment by MikuAuahDark** [comment]
Alright send the problematic mca file and I'll take a look tomorrow.

**Comment by MikuAuahDark** [comment]
Apparently I was wrong. `.mca` files has to be read in special way. In short, no. lua-nbt does not support mca files.

Also related: https://github.com/MikuAuahDark/SnakeNBT/issues/1#issuecomment-2154048517
